### ISSUE TITLE
NUnit Test and MS Test Capabilities

### ISSUE THREAD

**Issue by ghost** [madskristensen/HelpExplorer#12]
There is no current way to determine the difference between NUnit and MS Test Capabilities. I ran HelpExplorer on a MS Test project and then renamed the capabilities file to MsTest... Then I ran on a  NUnit test project and compared the resulting files. There is not difference between Capabilities.  So, since I have NUnit test in the projecttypes.json it may need to be changes to just Test and then offer both NUnit and MSTest links and let the developer decide which links to navigate to. Or MS needs to add capabilities to the shipped templates so that the loaded project type can be better determined by HelpExplorer. 

We have the same issue with Class Libraries since they are for a given project type (say i.e. WPF) the (control, User Control, etc. libraries capabilities) are all the same.

[NUnit_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7637835/NUnit_CSharp_CPS_Capabilities.txt)
[MsTest_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7637836/MsTest_CSharp_CPS_Capabilities.txt)

[WPFLibrary_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7637874/WPFLibrary_CSharp_CPS_Capabilities.txt)

**Comment by madskristensen** [comment]
There's also xUnit

**Comment by ghost** [comment]
Here are the results of the xUnit, NUnit, and MSTest.  They all have the exact same capabilities.  I opened issue https://github.com/dotnet/project-system/issues/7807
In the issue I mentioned that the libraries have the same issue.
[WPFLibrary_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7641902/WPFLibrary_Capabilities.txt)
[WPFUserControlLibrary_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7641903/WPFUserControlLibrary_Capabilities.txt)
[WPFCustomControlLibrary_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7641904/WPFCustomControlLibrary_Capabilities.txt)

**Comment by ghost** [comment]
It would be nice if we could see what the base project was used to create the current project since it would have a value we could look for (i.e. xUnit, NUnit, MSTest) in the template name.

**Comment by ghost** [comment]
Here is https://github.com/drewnoakes response to submitted [issue](https://github.com/dotnet/project-system/issues/7807), and my response back.

@[drewnoakes](https://github.com/drewnoakes) response:
That sounds like a great extension.

I see two possible approaches here:

Query the project's package references to identify what testing framework(s) it uses.
Have the providers of those test frameworks add an MSBuild item (such as ProjectCapability) or property in their bundled .props/.targets files.
The downside of the second approach is that it relies upon the package maintainers making a change, and then the user of the extension having a new enough version of the package.

Therefore I believe the first approach is likely the best way forward here. Note that there's nothing stopping a project using more than one unit test library at a time.

My response:
@[drewnoakes](https://github.com/drewnoakes) thanks but tested number one and it will allow you to get which test package is used, but this same method does not work for which project type of WPF library since the package reference do not specify that the WPF library project is a Custom user control, user control, or just a library project. Do you have any sample C# code that would help [Mads](https://github.com/madskristensen) and I determine the difference?

**Comment by ghost** [comment]
Mads;

Please look at @[drewnoakes ](https://github.com/drewnoakes)last response under [project-system/issues/7807](https://github.com/dotnet/project-system/issues/7807)

He said:
Thanks for the extra information.

Note that from the project system's perspective there's no real difference between WPF class library, WPF custom control or WPF user control projects.

The contents of the .csproj are identical for all three. In fact, the only difference between those three and a WPF application is the OutputType is set to WinExe on the application.

The difference between these templates is the content they generate internally. But there's nothing stopping you creating a WPF class library and putting both a user control and a custom control in it.

@[drewnoakes ](https://github.com/drewnoakes)also shows a way to add the ProjectCapability to Solution Explorer that works cool, but he has a high version of the project system installed since my shows version 3 not 4 in both VS 2022 v17.0.2 and VS 2022 v17.1.0 preview 1.1:
![image](https://user-images.githubusercontent.com/67446778/144960535-0b9e2ea1-42d4-409e-8bd5-6e8baf7c9216.png)

@[drewnoakes ](https://github.com/drewnoakes)As an aside, you might find the following trick handy in VS if you're not already using it. Stick this in your project file and the project's capabilities will be displayed in Solution Explorer:

```
  <ItemGroup>
    <ProjectCapability Include="DiagnoseCapabilities" />
  </ItemGroup>
```
![image](https://user-images.githubusercontent.com/67446778/144960090-a934ad35-2b6f-4491-a13f-a6c5a7fb02c4.png)
