### ISSUE TITLE
Projecttypes.json, Filetypes.json hard to find

### ISSUE THREAD

**Issue by ghost** [madskristensen/HelpExplorer#13]
@madskristensen ;  I am working on the documentation and think we should we make it easier to find/edit the projecttypes.json and filetypes.json files. I say this since the HelpExplorer location on disk, is not easy to find for a new developer. On my machine it is located at:

`C:\Users\DannyMcNaught\AppData\Local\Microsoft\VisualStudio\17.0_d55b22d5Exp\Extensions\Mads Kristensen\Help Explorer\1.0\Schema`. 

So would it be better to have the installation location added to _**HelpExplorer/Options/General.cs**_ so that it is available to find the location and even be able to open and edit the file in the current instance of Visual Studio where it is installed. As far as opening the json we could add a button to HelpExplorer toolwindow to open/edit the file

If you agree I will make this change

**Comment by ghost** [comment]
@madskristensen; I will follow these instructions unless the `Community.VisualStudio.Toolkit` has this build in.
[Add a toolbar to a tool window](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-toolbar-to-a-tool-window?view=vs-2022)

**Comment by madskristensen** [comment]
@SFC-Sarge It is higly unlikely that anyone would make changes to the json files. People who know what to change in them, wouldn't be users of Help Explorer to begin with. Let's not add this added complexity

**Comment by ghost** [comment]
@madskristensen;  OK
