### ISSUE TITLE
Add a toolbar to a HelpExplorer tool window

### ISSUE THREAD

**Issue by ghost** [madskristensen/HelpExplorer#14]
@madskristensen; I agree with the complexity on editing the json files, but what about adding a toolbar to the toolwindow that will turn on or off Multiple Project view (currently set in HelpExplorer/Options/Display Multiple Types)? This would make it easier for a user to display or not display the Multiple Project/File Types views in HelpExplorer and would not be too complex to the user interface. I would leave the current options settings and just make it easier to change from the HelpExplorer toolwindow.

**Comment by ghost** [comment]
@madskristensen; I am sorry my mind never stops thinking, why I was a Solution Architect, Solution Developer, and Contractor for the USPS for 20 years.

**Comment by ghost** [comment]
@madskristensen; I could not get it to work with the Community.VisualStudio.Toolkit. I opened Community.VisualStudio.Toolkit issue:
[How to add Toolbar and buttons to the Toolbar in a ToolWindow #241](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/241)

I also: Suggest it as a new show for the [Hacking Visual Studio show](https://www.youtube.com/playlist?list=PLReL099Y5nReXKzeX10TZF3BfLdOZXxix)

**Comment by madskristensen** [comment]
Adding a toolbar is probably a fine idea actually. We can use that for other things going forward too

**Comment by ghost** [comment]
@madskristensen; So, when do we expect this on the show: [Hacking Visual Studio show](https://www.youtube.com/playlist?list=PLReL099Y5nReXKzeX10TZF3BfLdOZXxix)? 
![image](https://user-images.githubusercontent.com/67446778/145446633-1c9b70d6-66a4-48e6-8d13-4e775e6ec904.png)

**Comment by ghost** [comment]
@madskristensen; Although the toolbar and button's themes are not `toolkit:Themes.UseVsTheme="True"`, I found the issue with the events not firing. It had to do with where I add the toolbar control in xaml.  It cannot be behind or under the ScrollViewer when it runs, or the toolbar does not get the click event.  I am working on the icons and popup description when you hover over the button. The buttons work, when the MutlipleProjectTypes event is fired it changes from Mutiliple to single project showing in the HelpExplorer window as well as set the Options.

It is a backdoor VS hack until you add the ability to the `Community.VisualStudio.Toolkit`.

**Comment by ghost** [comment]
@madskristensen; Setting the theme was easy using the Toolkit... just do this:        

`Themes.SetUseVsTheme(toolBar, true)`;     

Example:
```
        private void CreateToolBarButtons(ToolBar toolBar)
        {
            Themes.SetUseVsTheme(toolBar, true);
            if (!toolBar.HasItems)
            {
                var button1 = new Button() { Name = "MultipleProjectsTypes", Width = 25, Height = 25, Content = "MP" };
                button1.Click += MultipleProjectsTypes_Click;
                Themes.SetUseVsTheme(button1, true);
                toolBar.Items.Add(button1);
                var button2 = new Button() { Name = "MultipleFileTypes", Width = 25, Height = 25, Content = "MF" };
                button2.Click += MultipleFileTypes_Click;
                Themes.SetUseVsTheme(button2, true);
                toolBar.Items.Add(button2);
                var button3 = new Button() { Name = "CreateCapabilitesFile", Width = 25, Height = 25, Content = "CC" };
                button3.Click += CreateCapabilitesFile_Click;
                Themes.SetUseVsTheme(button3, true);
                toolBar.Items.Add(button3);
            }
        }
```

**Comment by ghost** [comment]
@madskristensen; Since the values I check and use for these buttons are true/false, I change from Button to ToggleButton.

I am now working on adding icons to the ToggleButtons so that they look more light VS.
```
        private void CreateToolBarButtons(ToolBar toolBar)
        {
            Themes.SetUseVsTheme(toolBar, true);
            if (!toolBar.HasItems)
            {
                var toggleButton1 = new ToggleButton() { Name = "MultipleProjectsTypes", Width = 25, Height = 25, Content = "MP", IsThreeState = false, IsChecked = General.Instance.MultipleProjectsOption };
                toggleButton1.Click += MultipleProjectsTypes_Click;
                Themes.SetUseVsTheme(toggleButton1, true);
                toolBar.Items.Add(toggleButton1);
                var toggleButton2 = new ToggleButton() { Name = "MultipleFileTypes", Width = 25, Height = 25, Content = "MF", IsThreeState = false, IsChecked = General.Instance.MultipleFilesOption };
                toggleButton2.Click += MultipleFileTypes_Click;
                Themes.SetUseVsTheme(toggleButton2, true);
                toolBar.Items.Add(toggleButton2);
                var toggleButton3 = new ToggleButton() { Name = "CreateCapabilitesFile", Width = 25, Height = 25, Content = "CC", IsThreeState = false, IsChecked = General.Instance.CreateCapabilitiesFile };
                toggleButton3.Click += CreateCapabilitesFile_Click;
                Themes.SetUseVsTheme(toggleButton3, true);
                toolBar.Items.Add(toggleButton3);
            }
        }
```

```
        private void MultipleProjectsTypes_Click(object sender, RoutedEventArgs e)
        {
            if (((ToggleButton)e.OriginalSource).IsChecked == true)
            {
                General.Instance.MultipleProjectsOption = true;
                General.Instance.Save();
            }
            else
            {
                General.Instance.MultipleProjectsOption = false;
                General.Instance.Save();
            }
            UpdateProjects(Hierarchy);
            e.Handled = true;
        }
```

        private void MultipleFileTypes_Click(object sender, RoutedEventArgs e)
        {
            if (((ToggleButton)e.OriginalSource).IsChecked == true)
            {
                General.Instance.MultipleFilesOption = true;
                General.Instance.Save();
            }
            else
            {
                General.Instance.MultipleFilesOption = false;
                General.Instance.Save();
            }
            e.Handled = true;
        }

```
        private void CreateCapabilitesFile_Click(object sender, RoutedEventArgs e)
        {
            if (((ToggleButton)e.OriginalSource).IsChecked == true)
            {
                General.Instance.CreateCapabilitiesFile = true;
                General.Instance.Save();
            }
            else
            {
                General.Instance.CreateCapabilitiesFile = false;
                General.Instance.Save();
            }
            e.Handled = true;
        }
```
