### ISSUE TITLE
Suggest you use GetActiveProjectcapabilities not GUID to determine Project Type.

### ISSUE THREAD

**Issue by ghost** [madskristensen/HelpExplorer#2]
Mads;

After watching your show last week, I tried to see if I could understand this project.  I could not get it to work as it was since I am only using VS 2022 and the new SDK project style the GUID method always returns C# on C# project but would not return WPF, etc.  So I looked into the Community,VisualStudio.Toolkit and it also would not return WPF then I found The Toolkit "[BUG] IsKindAsync not working [for me?] #160" issue and the suggested workaround using:
HierarchyUtilities.TryGetHierarchyProperty<string>(hierarchy, itemId, (int)__VSHPROPID5.VSHPROPID_ProjectCapabilities, out string value);
//The following capabilities line allows you to check the projects capabilities so they can be added to project.json.
            string[] capabilities = (value ?? "").Split(' ');

So based on that I updated your MyToolWindowControl.xaml.cs class not to use the GUID of the project but check the Capabilities. I also changed the project.json to use the Capabilities instead of GUID and the attach is working for me.  Please consider changing your code. This makes it easy to look up the project type without having to know the GUID of a project. 

Thanks to https://github.com/reduckted for his suggestions to fix the SDK style project by using Project Capabilities.

[MyToolWindowControl.xaml.zip](https://github.com/madskristensen/HelpExplorer/files/7535720/MyToolWindowControl.xaml.zip)

**Comment by ghost** [comment]
This also works in the project.json file to determine:  Project is CSharp And NetCore.

"projects": [ "CSharp & CPS" ],

**Comment by madskristensen** [comment]
Great idea. We probably need to support both Guids and project capabilities to support both CPS and legacy style project systems

**Comment by ghost** [comment]
Thanks Mads;

I also got the hyperlinks working as follows:

    private void UpdateProjects()
    {
        Widgets.Children.Clear();
        
        foreach (Widget widget in _projects.Widgets)
        {
            try
            {
                if ( !hierarchy.IsCapabilityMatch(widget.Projects.First()))
                {
                    continue;
                }

                var text = new Label { Content = widget.Text };
                Widgets.Children.Add(text);

                foreach (Link link in widget.Links)
                {
                    Hyperlink h = new Hyperlink();
                    h.NavigateUri = new Uri(link.Url);
                    h.RequestNavigate += OnRequestNavigate;
                    h.Inlines.Add(link.Text);
                    var textBlock = new TextBlock();
                    textBlock.Inlines.Add(h);

                    //var hyperlink = new Label { Content = link.Text };
                    Widgets.Children.Add(textBlock);
                }
            }
            catch (Exception ex)
            {
                ex.Log();
            }
        }
    }
    private void OnRequestNavigate(object sender, RequestNavigateEventArgs e)
    {
        // for .NET Core you need to add UseShellExecute = true
        var pStartInfo = new ProcessStartInfo(e.Uri.AbsoluteUri)
        {
            UseShellExecute = true
        };
        Process.Start(pStartInfo);
        e.Handled = true;
    }

**Comment by madskristensen** [comment]
Awesome. Send a PR!!!

**Comment by ghost** [comment]
Mads;
I originally cloned this repo.  It will not let me create a Pull Request, and if I try to push VS returns 403 for your repo.  I am not sure how to create the Pull Request for this issue. I tried following the documentation, but it does not get me anywhere.

**Comment by ghost** [comment]
Mads;
I forked the master and it then let me create a Pull Request.  Note: My code still does not keep the GUID since I currently do not have any way to test it without VS 2019 installed.
