### ISSUE TITLE
System.NullReferenceException on Xaml File

### ISSUE THREAD

**Issue by ghost** [madskristensen/HelpExplorer#7]
Double click the xaml file causes System.NullReferenceException in HelpExplorer
![DoubleClickXamlFileInSolutionExplorer](https://user-images.githubusercontent.com/67446778/142713906-5c853723-3aa3-47f4-ad40-d43bb835e79e.jpg)
:

**Comment by madskristensen** [comment]
On a designer surface, there is no text buffer. That's why it's null. I'm starting to realize that instead of using the content type, we should probably just go by file extension instead. It makes it much simpler and the result is the same

**Comment by ghost** [comment]
Mads do you want me to make this change from content type to file extension?

**Comment by madskristensen** [comment]
@SFC-Sarge if you want to do that, that would be awesome!!

**Comment by ghost** [comment]
Have provided fix to Mads.
